### PR TITLE
docs: teaseing with an image

### PR DESCRIPTION
**Pull request by jmfayard**
Help people to want to click on the documentation website

Made with https://carbon.now.sh

Code:

```kotlin
#!/usr/bin/env kotlin
// .github/workflows/github-action.main.kts

@file:DependsOn("it.krzeminski:github-actions-kotlin-dsl:VERSION")

workflow(
    name = "GitHub Action workflow - but YAML free 🎉",
    on = listOf(Push()),
    sourceFile = __FILE__.toPath(),
) {
    job(id = "my_job", runsOn = RunnerType.UbuntuLatest) {
        uses(name = "Check out",      action = CheckoutV3() )
        run( name = "Print greeting", command = "echo Hello world" )
    }
}.writeToFile()
```

### CODE REVIEW

**Comment by krzema12** [comment]
I guess you meant

```kotlin
#.github/workflows/github-action.main.kts
```

in the second line :)

**Comment by jmfayard** [comment]
right, I wrote a bash script today  :)

**Comment by jmfayard** [comment]
I don't see a setting for transparent background on https://carbon.now.sh/

**Comment by krzema12** [comment]
> I don't see a setting for transparent background on https://carbon.now.sh/

I think I found it!
IMG_20220617_180305

Could you try it out? I'm on mobile.

**Comment by jmfayard** [comment]
done but that's only for the margin, the code background is still in black

**Comment by krzema12** [comment]
Thanks! :tada:

**Pull request merged**
